import Modal from "@/components/Modal";
import { Inter } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./Provider";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trello Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${inter.className} bg-slate-50 dark:bg-[#0d1117] `}>
        <Providers attribute="class" defaultTheme="system" enableSystem>
          
          <main>{children}</main>
          <Modal />
        </Providers>
      </body>
    </html>
  );
}
